spring.application.name=colorapp
server.port=8080
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=colorapp
