pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
    }

    environment {
        JAVA_HOME = '/usr/lib/jvm/java-21-openjdk-amd64'
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
        APP_NAME = "color-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/sumanthrao04/end-to-end-devsecops-pipeline-java-app.git'
            }
        }

        stage('Check Java') {
            steps {
                sh 'which java'
                sh 'java -version'
                sh 'which javac'
                sh 'javac -version'
                sh 'mvn -version'
            }
        }

        stage('Build') {
            steps {
                dir('app/colorapp') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('app/colorapp') {
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('app/colorapp') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
               sh 'docker build -t ${APP_NAME}:${IMAGE_TAG} -f app/colorapp/Dockerfile .'
            }
        }
    }
}